--DEADLOCK
BEGIN TRAN

UPDATE BooksForSale
SET Price = 56 WHERE Id = 6

SELECT @@TRANCOUNT

UPDATE BooksForSale
SET DateOfPublishing = '8/27/2000' WHERE Id = 1

ROLLBACK TRAN


--READ UNCOMMITED => Dirty Read
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRAN

SELECT * FROM BooksForSale

ROLLBACK TRAN


--READ COMMITED => Non-repeteable Read
BEGIN TRAN

UPDATE BooksForSale
SET Price = 64 WHERE Id = 6

SELECT * FROM BooksForSale

COMMIT TRAN
ROLLBACK TRAN

--REPEATABLE READ => Phantom Read
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRAN

SELECT * FROM BooksForSale

SELECT * FROM BooksForSale

ROLLBACK TRAN

--SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRAN

SELECT * FROM BooksForSale

UPDATE BooksForSale
SET DateOfPublishing = '8/26/2000' WHERE Id = 9

SELECT * FROM BooksForSale

COMMIT TRAN
